In [1]:
import pandas as pd
import numpy as np
import time
import glob
from analysis import read_label,read_input

In [2]:
inputs = read_input()
labels = read_label()

read_input 52.824
read_label 1.154

In [3]:
inputs['1']['a']

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.88,1,-0.067731,-0.077242,-0.994709,-0.261408,-0.126591,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,0,0.017,0.88,1,-0.072668,-0.074727,-0.994553,-0.249771,-0.095830,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,0,0.033,0.88,1,-0.073926,-0.073448,-0.994555,-0.261276,-0.081169,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,0,0.050,0.88,1,-0.073949,-0.098539,-0.992382,-0.275582,-0.086266,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,0,0.067,0.88,1,-0.094782,-0.114583,-0.988882,-0.258371,-0.052407,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58013,58014,0,967.850,0.93,1,-0.176707,-0.191976,-0.965360,-0.224183,-0.221350,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
58014,58015,0,967.867,0.93,1,-0.179447,-0.180783,-0.967014,-0.226443,-0.209580,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
58015,58016,0,967.884,0.98,1,-0.183579,-0.177056,-0.966928,-0.230231,-0.205193,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
58016,58017,0,967.900,0.98,1,-0.184110,-0.175312,-0.967145,-0.230197,-0.203308,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
58017,58018,0,967.917,0.98,1,-0.187122,-0.175184,-0.966590,-0.233507,-0.202900,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0

In [4]:
labels['1']['a']['smile']

0        0
1        0
2        0
3        0
4        0
        ..
58013    0
58014    0
58015    0
58016    0
58017    0
Length: 58018, dtype: int64

In [26]:

columns = ['confidence','success','AU01_r', 'AU02_r', 'AU04_r', 'AU05_r', 'AU06_r', 'AU07_r', 'AU09_r', 'AU10_r', 'AU12_r', 'AU14_r', 'AU15_r', 'AU17_r', 'AU20_r', 'AU23_r', 'AU25_r', 'AU26_r', 'AU45_r','AU01_c', 'AU02_c', 'AU04_c', 'AU05_c', 'AU06_c', 'AU07_c', 'AU09_c', 'AU10_c', 'AU12_c', 'AU14_c', 'AU15_c', 'AU17_c', 'AU20_c', 'AU23_c', 'AU25_c', 'AU26_c', 'AU28_c', 'AU45_c']

action_name = 'smile'
X = pd.DataFrame()
Y = pd.Series()
for video in ['1','2']:
    for person in ['a','b','c']:
        X = X.append(inputs[video][person][columns])
        Y = Y.append(labels[video][person][action_name])

# covert from Int64Index to RangeIndex
X.reset_index(inplace=True)
Y.reset_index(inplace=True,drop=True)

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            19609, 19610, 19611, 19612, 19613, 19614, 19615, 19616, 19617,
            19618],
           dtype='int64', length=232911)
RangeIndex(start=0, stop=232911, step=1)

In [24]:
from sklearn.model_selection import train_test_split

33709

In [7]:
from sklearn.neural_network import MLPClassifier

,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,AU09_r,AU10_r,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
count,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,...,58018.000000,58018.00000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000
mean,0.972083,0.998793,0.161612,0.131521,0.523083,0.105851,0.334737,0.367082,0.103448,0.050026,...,0.529181,0.40122,0.169447,0.398376,0.149419,0.201972,0.353287,0.161881,0.003723,0.316902
std,0.039676,0.034714,0.278774,0.316178,0.389538,0.272148,0.479017,0.541950,0.224039,0.169595,...,0.499152,0.49015,0.375150,0.489568,0.356504,0.401475,0.477995,0.368345,0.060903,0.465273
min,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.980000,1.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.980000,1.000000,0.000000,0.000000,0.490000,0.000000,0.040000,0.010000,0.000000,0.000000,...,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.980000,1.000000,0.250000,0.030000,0.790000,0.000000,0.550000,0.610000,0.090000,0.000000,...,1.000000,1.00000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,0.980000,1.000000,3.290000,2.690000,2.060000,2.150000,2.090000,3.850000,2.170000,1.640000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [35]:
a.head()

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.88,1,-0.067731,-0.077242,-0.994709,-0.261408,-0.126591,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,0,0.017,0.88,1,-0.072668,-0.074727,-0.994553,-0.249771,-0.095830,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,0,0.033,0.88,1,-0.073926,-0.073448,-0.994555,-0.261276,-0.081169,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,0,0.050,0.88,1,-0.073949,-0.098539,-0.992382,-0.275582,-0.086266,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,0,0.067,0.88,1,-0.094782,-0.114583,-0.988882,-0.258371,-0.052407,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0

In [30]:
a.drop_duplicates(inplace=True)

In [38]:
a.describe()

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
count,58018.000000,58018.0,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,...,58018.000000,58018.00000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000,58018.000000
mean,29009.500000,0.0,483.958483,0.972083,0.998793,0.225336,0.104294,-0.946681,0.074207,0.105743,...,0.529181,0.40122,0.169447,0.398376,0.149419,0.201972,0.353287,0.161881,0.003723,0.316902
std,16748.498296,0.0,279.420780,0.039676,0.034714,0.189330,0.049637,0.051236,0.192335,0.052377,...,0.499152,0.49015,0.375150,0.489568,0.356504,0.401475,0.477995,0.368345,0.060903,0.465273
min,1.000000,0.0,0.000000,0.030000,0.000000,-0.518756,-0.268152,-0.999939,-0.639355,-0.284049,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14505.250000,0.0,241.979250,0.980000,1.000000,0.137532,0.077964,-0.981088,-0.023948,0.076711,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29009.500000,0.0,483.958500,0.980000,1.000000,0.251661,0.108784,-0.960889,0.095929,0.109098,...,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,43513.750000,0.0,725.937750,0.980000,1.000000,0.352141,0.140828,-0.923184,0.203931,0.142141,...,1.000000,1.00000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,58018.000000,0.0,967.917000,0.980000,1.000000,0.627876,0.418232,0.000000,0.535078,0.385075,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000